[VIM-7179] Fixes for UserItem and updates for Folder models
vimeo/VimeoNetworking pull request #350
Opened 2019-08-27 16:58 UTC by asongvimeo

#### Ticket

[VIM-7179](https://vimean.atlassian.net/browse/VIM-7179)

- *Note: this is required for Vimeo staff only. If not applicable to your PR, use "N/A".*

#### Pull Request Checklist

- [x] Resolved any merge conflicts
- [x] No build errors or warnings are introduced
- [x] New files are written in Swift
- [x] New classes contain license headers
- [x] New classes have Documentation
- [x] New public methods have Documentation

#### Issue Summary

- UserItemType not mapping correctly on UserItem
- Folder 

#### Implementation Summary

- UserItem: Added missing mapping logic for the UserItemType property.
- Folder: Added missing logic for converting the date string to date types.

#### Reviewer Tips

- n/a

#### How to Test

- n/a

2019-08-27 17:07 UTC, cameo-github commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">SwiftLint not installed, download from https://github.com/realm/SwiftLint</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 117 tests, with 0 failures (0 unexpected) in 0.675 (0.733) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/VimeoNetworking/1213)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2019-08-27 22:39 UTC, bryantjustin requested changes
As per our conversation, we shouldn't have to convert between ISO8601 string to `NSDate`. All those properties should be changed.

2019-08-27 22:39 UTC, bryantjustin commented on Sources/Shared/Models/Folder.swift
> +    @objc public private(set) var createdTimeString: String?
Not necessary. Just use `createdTime` and type it as `Date`.

2019-08-27 22:39 UTC, bryantjustin commented on Sources/Shared/Models/Folder.swift
>      @objc public private(set) var modifiedDate: Date?
`modifiedDate` and `createdDate` can probably be removed.

2019-08-27 22:39 UTC, bryantjustin commented on Sources/Shared/Models/Folder.swift
> +    private func formatDate(from dateString: String?) -> Date? {
You can remove this. In the future if you're copying something like this, you should really consider refactoring the method into a protocol as opposed to copying and pasting.

2019-08-27 22:39 UTC, bryantjustin commented on Sources/Shared/Models/UserItem.swift
> +extension UserItem {
This one can be `private`, or combined with the previous extension and make the struct `private`

2019-09-03 14:10 UTC, bryantjustin approved these changes
👍

2019-09-03 18:36 UTC, merged