[WIP] VIM-7221: Replaces AFNetworking's reachability manager
vimeo/VimeoNetworking pull request #351
Opened 2019-08-28 21:16 UTC by rpassis

#### Ticket

[VIM-7221](https://vimean.atlassian.net/browse/VIM-7221)

#### Pull Request Checklist

- [X] Resolved any merge conflicts
- [X] No build errors or warnings are introduced
- [X] New files are written in Swift
- [X] New classes contain license headers
- [X] New classes have Documentation
- [X] New public methods have Documentation

#### Issue Summary

As part of the project to remove our dependency on AFNetworking, there are some key components that we will need to replace, one of each is the AFReachabilityManager class.

The goal of this PR is to introduce the replacement for this class that does not depend on third party libraries, and is written in Swift.

#### Implementation Summary

There are several implementations of Reachability available online, and our solution is heavily based in one of them - the basis of our `NetworkReachabilityManager` was taken from [Alamofire](https://raw.githubusercontent.com/Alamofire/Alamofire/master/Source/NetworkReachabilityManager.swift) and modified to our needs.

Most of the implementation of this class is to be kept internal to the framework, and we have refactored `VimeoReachability` into `VimeoReachabilityMonitor`, and exposed the basic functionality required by consumers of the API through this class.

In addition to that, a new protocol `ReachabilityMonitoring` was created, and `VimeoClient` was refactored to be able to injest it as a dependency.

#### Unit tests

TBC

#### How to Test

TBC

2019-08-28 21:27 UTC, cameo-github commented
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">SwiftLint not installed, download from https://github.com/realm/SwiftLint</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 117 tests, with 0 failures (0 unexpected) in 1.048 (1.195) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/VimeoNetworking/1216)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

2019-09-04 18:38 UTC, bryantjustin requested changes
A few small comments/suggestions. Looks good for the most part.

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/VimeoReachability.swift
> -//
Good riddance. 👋

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/Reachability/NetworkReachabilityManager.swift
> +public protocol ReachabilityManagingType {
Is there a reason to prefer `ReachabilityManagingType` over simply `ReachabilityManaging`?

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/Reachability/NetworkReachabilityManager.swift
> +    private var previousStatus: NetworkReachabilityStatus?
Ahh this is why you were asking for the synchronization mechanism.

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/VimeoClient.swift
> +    private var reachabilityMonitor: ReachabilityManagingType?
Why the change in name here to `rechabilityMonitor`?

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/VimeoClient.swift
> +        reachabilityMonitor: ReachabilityManagingType? = VimeoReachabilityProvider.reachabilityManager
Should we maybe switch the order of the parameters so trailing-closure syntax could be taken advantage of?

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/VimeoClient.swift
> +        completionQueue: DispatchQueue = DispatchQueue.main,
Nit: thoughts on just doing:
```suggestion
        completionQueue: DispatchQueue = .main,
```

2019-09-04 18:38 UTC, bryantjustin commented on Sources/Shared/VimeoClient.swift
> +        reachabilityMonitor: ReachabilityManagingType? = VimeoReachabilityProvider.reachabilityManager
Another spot where we could swap parameter orders to allow trailing-closure syntax at the invocation site.

2019-09-04 18:38 UTC, bryantjustin commented on Tests/Shared/Reachability/NetworkReachabilityStatusTests.swift
> +
Nit: extraneous spaces here

2019-09-04 18:38 UTC, bryantjustin commented on Tests/Shared/Reachability/NetworkingReachabilityManagerTests.swift
> +
Nit: extra space.

2019-09-04 18:38 UTC, bryantjustin commented on Tests/Shared/Reachability/NetworkingReachabilityManagerTests.swift
> +    func testThatManagerCanBeInitializedFromHost() {
The test methods here don't seem to follow our format in the style [guide](https://github.vimeows.com/MobileApps/Style-Guides/tree/master/Apple#naming-unit-tests).

2019-09-04 19:51 UTC, bryantjustin approved these changes
LGTM.

2019-09-04 19:51 UTC, merged