Add email field to VIMUser object
vimeo/VimeoNetworking pull request #413
Opened 2020-03-10 14:41 UTC by antonklevets

#### Ticket

[908](https://vimean.atlassian.net/browse/VCI-908)

#### Pull Request Checklist

- [x] Resolved any merge conflicts
- [x] No build errors or warnings are introduced
- [x] New files are written in Swift
- [x] New classes contain license headers
- [x] New classes have Documentation
- [x] New public methods have Documentation

#### Issue Summary

- Should allow get user email

#### Implementation Summary

- Add `email` field to VIMUser object

#### Reviewer Tips

N/A

#### How to Test

N/A

2020-03-10 14:43 UTC, gennadiiivanov approved these changes

2020-03-10 14:44 UTC, gennadiiivanov commented on Sources/Shared/Models/VIMUser.h
> +@property (nonatomic, copy, nullable) NSString *email;
let's keep empty space to save the structure

2020-03-10 14:44 UTC, gennadiiivanov commented
Let's wait for approval from @rpassis

2020-03-10 14:44 UTC, rpassis commented
Please hold off on merging this. I'll approve once I clarified something offline.

2020-03-10 16:07 UTC, cameo-github commented
<!--
  0 Errors
  4 Warnings: Skipping duplicate build file ...
  1 Message: Executed 231 tests, with 0 fai...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Skipping duplicate build file in Compile Sources build phase: /Users/distiller/VimeoNetworking/Sources/Shared/Requests/Request+Apple.swift (in target ‘VimeoNetworking-iOS’ from project ‘VimeoNetworking’)</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><strong><a href="https://github.com/vimeo/VimeoNetworking/blob/2af33efcd8a644107edeb58d42fdf33f19e4967e/Sources/Shared/Requests/Request+PublishToSocial.swift#L46">Sources/Shared/Requests/Request+PublishToSocial.swift#L46</a></strong>: expression implicitly coerced from ‘String?’ to ‘Any’  <br /><code>
                .title: $0.title,
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><strong><a href="https://github.com/vimeo/VimeoNetworking/blob/2af33efcd8a644107edeb58d42fdf33f19e4967e/Sources/Shared/Requests/Request+PublishToSocial.swift#L47">Sources/Shared/Requests/Request+PublishToSocial.swift#L47</a></strong>: expression implicitly coerced from ‘String?’ to ‘Any’  <br /><code>
                .description: $0.description,
</code></td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><strong><a href="https://github.com/vimeo/VimeoNetworking/blob/2af33efcd8a644107edeb58d42fdf33f19e4967e/Sources/Shared/Requests/Request+PublishToSocial.swift#L79">Sources/Shared/Requests/Request+PublishToSocial.swift#L79</a></strong>: expression implicitly coerced from ‘String?’ to ‘Any’  <br /><code>
                .categoryID: $0.categoryID
</code></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 231 tests, with 0 failures (0 unexpected) in 0.963 (1.202) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/VimeoNetworking/1678)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-03-10 17:03 UTC, gennadiiivanov commented
@rpassis take a look now please

2020-03-10 17:54 UTC, rpassis requested changes
Hi there, apologies but it turns out my suggestion to use the `emails` field was not a good one. That field is used for email addresses other than the primary one so let's just revert this latest change.

2020-03-10 17:54 UTC, rpassis commented on Sources/Shared/Models/VIMUser.m
> +
```suggestion
```

2020-03-10 19:13 UTC, gennadiiivanov commented on Sources/Shared/Models/VIMUser.m
> +
👍

2020-03-10 19:51 UTC, gennadiiivanov commented
@antonklevets let's try 2 different options in our repository:
1. Preferred: subclass User object and add email property to it.
2. Add private category for user object that includes "email" property.

2020-03-11 10:01 UTC, antonklevets commented
> @antonklevets let's try 2 different options in our repository:
> 
> 1. Preferred: subclass User object and add email property to it.
> 2. Add private category for user object that includes "email" property.

We can't.
1. Subclass don't help me, because framework parse `VIMUser` object
2. Category don't support variables

2020-03-11 12:27 UTC, rpassis commented
Hey @antonklevets can you point me to where/how you are making a request that returns a `VIMUser`? We may be able to get around that but I need more details on how you are obtaining the user that you currently need an email attribute for.

```

2020-03-11 13:04 UTC, antonklevets commented
> Hey @antonklevets can you point me to where/how you are making a request that returns a `VIMUser`? We may be able to get around that but I need more details on how you are obtaining the user that you currently need an email attribute for.

Hey @rpassis I get `email` when call `getMeRequest` method and after login/create account, i.e. `vimeoClient.currentAccount?.user?.email`

2020-03-11 14:21 UTC, antonklevets commented
@rpassis Don't you like `email` public property? I can make private property and get `email` via `keyValueDictionary` in our extension  if you ok

2020-03-11 20:30 UTC, rpassis approved these changes

2020-03-12 08:43 UTC, merged